from pathlib import Path

path = Path('.github/tmp_apply_s2_review_linkage_826.py')
text = path.read_text(encoding='utf-8')
start = text.index('# Shared patch helper: hydrate canonical review SHA from record-level neutral ownership.\n')
end = text.index('# 2) Core S2 validator hydrates canonical_review_ref and validates under the correct name.\n')
replacement = '''# Shared patch helper: hydrate canonical review SHA from record-level neutral ownership.\ndef add_review_hydration(text: str, *, label: str, mode: str) -> str:\n    anchor = \'\'\'    for key, value in record_level.items():\\n\'\'\'\n    start = text.find(anchor)\n    if start < 0:\n        raise SystemExit(f"{label}: record_level loop anchor missing")\n    row_loop = \'\'\'    for key, value in row.items():\\n\'\'\'\n    insert_at = text.find(row_loop, start)\n    if insert_at < 0:\n        raise SystemExit(f"{label}: derived row loop anchor missing")\n    if mode == "fail":\n        block = \'\'\'    raw_harness = record.get("canonical_harness_id")\n    if raw_harness is not None:\n        canonical_review_ref = record.get("canonical_review_ref")\n        if not isinstance(canonical_review_ref, str) or not canonical_review_ref:\n            fail(f"{row.get(\'observation_id\')}: canonical neutral raw record missing canonical_review_ref")\n        if "canonical_review_ref" in hydrated and hydrated["canonical_review_ref"] != canonical_review_ref:\n            fail(f"{row.get(\'observation_id\')}: canonical_review_ref raw field conflict")\n        hydrated["canonical_review_ref"] = canonical_review_ref\n\'\'\'\n    elif mode == "require":\n        block = \'\'\'    raw_harness = record.get("canonical_harness_id")\n    if raw_harness is not None:\n        canonical_review_ref = record.get("canonical_review_ref")\n        require(\n            isinstance(canonical_review_ref, str) and bool(canonical_review_ref),\n            f"{row.get(\'observation_id\')}: canonical neutral raw record missing canonical_review_ref",\n        )\n        require(\n            "canonical_review_ref" not in hydrated\n            or hydrated["canonical_review_ref"] == canonical_review_ref,\n            f"{row.get(\'observation_id\')}: canonical_review_ref raw field conflict",\n        )\n        hydrated["canonical_review_ref"] = canonical_review_ref\n\'\'\'\n    else:\n        raise SystemExit(f"{label}: unsupported hydration mode {mode!r}")\n    if "canonical neutral raw record missing canonical_review_ref" in text:\n        raise SystemExit(f"{label}: canonical review hydration already present")\n    return text[:insert_at] + block + text[insert_at:]\n\n'''
text = text[:start] + replacement + text[end:]
text = text.replace('add_review_hydration(text, label="S2 validate", require_name="fail")', 'add_review_hydration(text, label="S2 validate", mode="fail")')
text = text.replace('add_review_hydration(text, label="S2 primary closure", require_name="require")', 'add_review_hydration(text, label="S2 primary closure", mode="require")')
text = text.replace('add_review_hydration(text, label="S2 matched closure", require_name="require")', 'add_review_hydration(text, label="S2 matched closure", mode="require")')
path.write_text(text, encoding='utf-8')
print('fixed #826 assembler hydration helper')
