#!/usr/bin/env python3
"""Render the autonomy-centered VSM TLDR projection."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


TLDR_BEGIN = "<!-- BEGIN GENERATED VSM TLDR -->"
TLDR_END = "<!-- END GENERATED VSM TLDR -->"


def read_catalog(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle, delimiter="|"))
    for row in rows:
        row["vsm_tldr"] = row["vsm_tldr"].replace("\\n", "\n")
    return sorted(rows, key=lambda row: int(row["catalog_position"]))


def markdown(value: str) -> str:
    return " ".join(value.split()).replace("|", "\\|")


def markdown_multiline(value: str) -> str:
    rendered = []
    for line in value.splitlines():
        system, separator, description = line.partition(":")
        if separator:
            rendered.append(f"<strong>{markdown(system)}:</strong> {markdown(description)}")
        else:
            rendered.append(markdown(line))
    return "<br>".join(rendered)


def catalog_label(harness: dict[str, str]) -> str:
    year = harness["repository_created_at"][:4]
    label = markdown(f"{harness['project_name']} ({year})")
    return f"[{label}]({harness['repository']})"


def render_tldr_block(repo: Path) -> str:
    harnesses = [
        row
        for row in read_catalog(repo / "data" / "catalog.psv")
        if row.get("tldr_status", "included") == "included"
    ]
    lines = [
        TLDR_BEGIN,
        "<!-- Generated by scripts/render_tldr.py; edit data/catalog.psv. -->",
    ]
    if not harnesses:
        lines.append("No included VSM TL;DR fingerprints yet.")
    else:
        lines.extend(
            [
                "| Harness | VSM TL;DR |",
                "| --- | --- |",
            ]
        )
        for harness in reversed(harnesses):
            tldr = harness.get("vsm_tldr", "")
            lines.append(
                f"| {catalog_label(harness)} | {markdown_multiline(tldr)} |"
            )
    lines.append(TLDR_END)
    return "\n".join(lines)


def render_tldr_document(repo: Path) -> str:
    return "\n".join(
        [
            "# VSM Harness TL;DR",
            "",
            "Compact autonomy-centered fingerprints for the current discovery cohort.",
            "Every included row shows S1, S2, S3, S3*, S4, and S5.",
            "",
            "| Symbol | State | Meaning |",
            "| --- | --- | --- |",
            "| `A` | Agent-owned | Ready agent-owned enactment is available through the standard documented setup. |",
            "| `C` | Composable | A first-party primitive is supplied, but the developer must compose the agent, authority, or feedback loop. |",
            "| `P` | Parent-assisted | Runtime closure returns a parent identity or ultimate-policy decision to subsequent operation; valid only for S5. |",
            "| `—` | No supplied path | The review boundary supports no material first-party path; this is not proof that one can never be built. |",
            "| `?` | Unknown | The reviewed primary evidence is insufficient to establish the state. |",
            "",
            "Fingerprints are processed by ascending catalog position before",
            "cross-catalog distinctions are finalized. Rows are displayed by GitHub",
            "repository creation time, newest first. The displayed year is the repository creation",
            "year, not necessarily the first agent-capable release.",
            "",
            "Rows are evidence-backed catalog fingerprints. Projects whose standard",
            "documented setup does not establish an autonomous decision/action loop are",
            "excluded as NO AGENTIC VSM.",
            "See [methodology](METHODOLOGY.md) and",
            "[sources and licensing](SOURCES.md).",
            "",
            render_tldr_block(repo),
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    tldr_path = repo / "TLDR.md"
    rendered_tldr = render_tldr_document(repo)
    if args.check:
        if not tldr_path.exists() or tldr_path.read_text(encoding="utf-8") != rendered_tldr:
            raise SystemExit("TLDR projection is stale; run scripts/render_tldr.py")
        print("TLDR projection is current")
        return 0
    tldr_path.write_text(rendered_tldr, encoding="utf-8")
    print(tldr_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
