#!/usr/bin/env python3
"""Render the scored-assessment projection in README.md from derived CSV data."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


BEGIN = "<!-- BEGIN GENERATED SCORED ASSESSMENTS -->"
END = "<!-- END GENERATED SCORED ASSESSMENTS -->"
TLDR_BEGIN = "<!-- BEGIN GENERATED VSM TLDR -->"
TLDR_END = "<!-- END GENERATED VSM TLDR -->"
CURRENT_RUBRIC = "vsm-assessment/v2"
SCORE_METRICS = {
    "adoption": "adoption.readiness",
    "structure": "vsm.structural_completeness",
    "operation": "vsm.operational_maturity",
}


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def read_catalog(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle, delimiter="|"))
    for row in rows:
        row["vsm_tldr"] = row["vsm_tldr"].replace("\\n", "\n")
    return sorted(rows, key=lambda row: int(row["catalog_position"]))


def markdown(value: str) -> str:
    return " ".join(value.split()).replace("|", "\\|")


def markdown_multiline(value: str) -> str:
    rendered = []
    for line in value.splitlines():
        system, separator, description = line.partition(":")
        if separator:
            rendered.append(f"<strong>{markdown(system)}:</strong> {markdown(description)}")
        else:
            rendered.append(markdown(line))
    return "<br>".join(rendered)


def score(metric: dict[str, str] | None) -> str:
    if not metric or metric.get("availability") != "available":
        return "not assessed"
    raw, maximum = metric.get("value", ""), metric.get("max_value", "")
    if not raw or not maximum:
        return "not assessed"
    try:
        percentage = float(raw) / float(maximum) * 100
    except (TypeError, ValueError, ZeroDivisionError):
        return "not assessed"
    return f"{raw}/{maximum} ({percentage:.0f}%)"


def latest_assessments(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    latest: dict[str, dict[str, str]] = {}
    for row in rows:
        harness_id = row["harness_id"]
        candidate = (row.get("generated_at", ""), row.get("assessment_id", ""))
        incumbent = latest.get(harness_id)
        if incumbent is None or candidate > (
            incumbent.get("generated_at", ""),
            incumbent.get("assessment_id", ""),
        ):
            latest[harness_id] = row
    return sorted(
        latest.values(),
        key=lambda row: (
            int(row.get("catalog_position", "999999")),
            row.get("project_name", "").casefold(),
        ),
    )


def current_assessments(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    return latest_assessments(
        [row for row in rows if row.get("rubric_version") == CURRENT_RUBRIC]
    )


def harness_label(harness: dict[str, str]) -> str:
    name = harness.get("project_name", harness["harness_id"])
    return markdown(f"{name} ({harness.get('introduced_year', 'year unknown')})")


def catalog_label(harness: dict[str, str], detailed: bool) -> str:
    year = harness["repository_created_at"][:4]
    label = markdown(f"{harness['project_name']} ({year})")
    target = (
        f"entries/{harness['harness_id']}.md"
        if detailed
        else harness["repository"]
    )
    return f"[{label}]({target})"


def render_scored_block(repo: Path) -> str:
    harnesses = current_assessments(read_csv(repo / "data" / "harnesses.csv"))
    metrics = read_csv(repo / "data" / "harness-metrics.csv")
    by_assessment_and_metric = {
        (row["assessment_id"], row["metric_id"]): row for row in metrics
    }
    harnesses = [
        harness
        for harness in harnesses
        if any(
            (harness["assessment_id"], metric_id) in by_assessment_and_metric
            for metric_id in SCORE_METRICS.values()
        )
    ]

    lines = [
        BEGIN,
        "<!-- Generated by scripts/render_readme.py; edit assessment artifacts instead. -->",
    ]
    if not harnesses:
        lines.append("No current scored assessments yet.")
    else:
        lines.extend(
            [
                "| Harness | Snapshot | Rubric | Target projection readiness | Observed design | Observed operation | Verdict |",
                "| --- | --- | --- | ---: | ---: | ---: | --- |",
            ]
        )
        for harness in harnesses:
            assessment_id = harness["assessment_id"]
            values = {
                label: score(by_assessment_and_metric.get((assessment_id, metric_id)))
                for label, metric_id in SCORE_METRICS.items()
            }
            snapshot = f"{harness.get('ref', 'unknown')} @ {harness.get('generated_at', '')[:10]}"
            lines.append(
                "| "
                + " | ".join(
                    [
                        harness_label(harness),
                        markdown(snapshot),
                        markdown(harness.get("rubric_version", "unknown")),
                        values["adoption"],
                        values["structure"],
                        values["operation"],
                        markdown(harness.get("verdict", "unknown")),
                    ]
                )
                + " |"
            )
    lines.append(END)
    return "\n".join(lines)


def render_tldr_block(repo: Path) -> str:
    harnesses = [
        row
        for row in read_catalog(repo / "data" / "catalog.psv")
        if row.get("tldr_status", "included") == "included"
    ]
    assessments = {
        row["harness_id"]: row
        for row in current_assessments(read_csv(repo / "data" / "harnesses.csv"))
    }
    lines = [
        TLDR_BEGIN,
        "<!-- Generated by scripts/render_readme.py; edit data/catalog.psv or a detailed assessment override. -->",
    ]
    if not harnesses:
        lines.append("No current VSM TL;DR assessments yet.")
    else:
        lines.extend(
            [
                "| Harness | VSM TL;DR |",
                "| --- | --- |",
            ]
        )
        for harness in reversed(harnesses):
            detailed = harness["harness_id"] in assessments
            tldr = assessments.get(harness["harness_id"], harness).get("vsm_tldr", "")
            lines.append(
                f"| {catalog_label(harness, detailed)} | {markdown_multiline(tldr)} |"
            )
    lines.append(TLDR_END)
    return "\n".join(lines)


def render_tldr_document(repo: Path) -> str:
    return "\n".join(
        [
            "# VSM Harness TL;DR",
            "",
            "Compact autonomy-centered fingerprints for the current discovery cohort.",
            "Every included row shows S1, S2, S3, S3*, S4, and S5. `A` means",
            "agent-owned, `C` means a first-party primitive still requires composition,",
            "and `P` is reserved for parent-assisted S5 closure. `—` means the reviewed",
            "boundary supports no material first-party path; `?` means evidence is",
            "insufficient. Assessments are processed by ascending catalog position before",
            "cross-catalog distinctions are finalized. Rows are displayed by GitHub",
            "repository creation time, newest first. The displayed year is the repository creation",
            "year, not necessarily the first agent-capable release.",
            "",
            "Catalog-only rows are source-derived hypotheses. Projects without a",
            "confirmed first-party decision/action loop are excluded as NO AGENTIC VSM.",
            "Detailed assessments override them by `harness_id`. See [methodology](METHODOLOGY.md) and",
            "[sources and licensing](SOURCES.md).",
            "",
            render_tldr_block(repo),
            "",
        ]
    )


def replace_block(readme: str, begin: str, end: str, rendered: str) -> str:
    if readme.count(begin) != 1 or readme.count(end) != 1:
        raise ValueError(f"README must contain exactly one marker pair: {begin} / {end}")
    before, remainder = readme.split(begin, 1)
    _, after = remainder.split(end, 1)
    return before + rendered + after


def render_readme(repo: Path, readme: str) -> str:
    readme = replace_block(readme, BEGIN, END, render_scored_block(repo))
    if TLDR_BEGIN in readme or TLDR_END in readme:
        readme = replace_block(
            readme,
            TLDR_BEGIN,
            TLDR_END,
            "See the complete [VSM TL;DR catalog](TLDR.md).",
        )
    return readme


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    readme_path = repo / "README.md"
    tldr_path = repo / "TLDR.md"
    current = readme_path.read_text(encoding="utf-8")
    rendered = render_readme(repo, current)
    rendered_tldr = render_tldr_document(repo)
    if args.check:
        if rendered != current or not tldr_path.exists() or tldr_path.read_text(encoding="utf-8") != rendered_tldr:
            raise SystemExit("README or TLDR projection is stale; run scripts/render_readme.py")
        print("README and TLDR projections are current")
        return 0
    readme_path.write_text(rendered, encoding="utf-8")
    tldr_path.write_text(rendered_tldr, encoding="utf-8")
    print(readme_path)
    print(tldr_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
