#!/usr/bin/env python3
"""Render deterministic corpus-level analytics from canonical Index sources."""
from __future__ import annotations

import argparse
import csv
import re
from collections import Counter, defaultdict
from pathlib import Path
from typing import Callable

from render_tldr import base_state
from validate_tldr import load_assessments, validate_assessment, vector


FUNCTIONS = ("S1", "S2", "S3", "S3*", "S4", "S5")
STATES = ("A", "A(P)", "C", "C(P)", "P", "—", "?")
MATERIAL_STATES = {"A", "A(P)", "C", "C(P)", "P"}
AUTONOMOUS_STATES = {"A", "A(P)"}


def read_psv(path: Path) -> list[dict[str, str]]:
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="|"))


def load_included(repo: Path) -> list[tuple[str, list[str]]]:
    assessments = load_assessments(repo / "assessments")
    rows: list[tuple[str, list[str]]] = []
    for harness_id, assessment in assessments.items():
        validate_assessment(assessment)
        if assessment["status"] == "included":
            rows.append((harness_id, vector(assessment)))
    rows.sort(key=lambda item: item[0])
    if not rows:
        raise ValueError("cannot render analytics for an empty included corpus")
    return rows


def share(count: int, total: int) -> str:
    return f"{count} ({100.0 * count / total:.1f}%)"


def state_counts(vectors: list[list[str]]) -> list[Counter[str]]:
    return [Counter(states[index] for states in vectors) for index in range(len(FUNCTIONS))]


def autonomous_coverage(states: list[str]) -> int:
    return sum(base_state(state) == "A" for state in states)


def coverage_distribution(vectors: list[list[str]]) -> Counter[int]:
    return Counter(autonomous_coverage(states) for states in vectors)


def vector_frequency(vectors: list[list[str]]) -> Counter[tuple[str, ...]]:
    return Counter(tuple(states) for states in vectors)


def cooccurrence_matrix(
    vectors: list[list[str]], predicate: Callable[[str], bool]
) -> list[list[int]]:
    size = len(FUNCTIONS)
    matrix = [[0 for _ in range(size)] for _ in range(size)]
    for states in vectors:
        present = [predicate(state) for state in states]
        for left in range(size):
            if not present[left]:
                continue
            for right in range(size):
                if present[right]:
                    matrix[left][right] += 1
    return matrix


def changed_functions(row: dict[str, str]) -> set[str]:
    return set(re.findall(r"S3\*|S[1-5]", row.get("changed_functions", "")))


def validate_aggregates(vectors: list[list[str]]) -> None:
    total = len(vectors)
    detailed = state_counts(vectors)
    for function, counts in zip(FUNCTIONS, detailed):
        if sum(counts.values()) != total:
            raise ValueError(f"{function}: detailed ownership counts do not sum to corpus size")
        unknown_states = set(counts) - set(STATES)
        if unknown_states:
            raise ValueError(f"{function}: unknown ownership state(s): {sorted(unknown_states)}")

    if sum(coverage_distribution(vectors).values()) != total:
        raise ValueError("autonomous-coverage distribution does not sum to corpus size")
    if sum(vector_frequency(vectors).values()) != total:
        raise ValueError("ownership-vector frequency does not sum to corpus size")

    predicates = {
        "material": lambda state: state in MATERIAL_STATES,
        "autonomous": lambda state: state in AUTONOMOUS_STATES,
    }
    for label, predicate in predicates.items():
        matrix = cooccurrence_matrix(vectors, predicate)
        for left in range(len(FUNCTIONS)):
            expected_diagonal = sum(predicate(states[left]) for states in vectors)
            if matrix[left][left] != expected_diagonal:
                raise ValueError(f"{label} co-occurrence diagonal mismatch for {FUNCTIONS[left]}")
            for right in range(len(FUNCTIONS)):
                if matrix[left][right] != matrix[right][left]:
                    raise ValueError(
                        f"{label} co-occurrence is not symmetric at "
                        f"{FUNCTIONS[left]}/{FUNCTIONS[right]}"
                    )


def generated_preamble(title: str, total: int) -> list[str]:
    return [
        f"# {title}",
        "",
        "Generated by `scripts/render_analytics.py` from canonical Index sources. Do not edit manually.",
        "",
        f"Included corpus denominator: **{total} harnesses**.",
        "",
        "Ownership states are categorical arrangements, not a maturity or product-quality ladder.",
        "",
    ]


def render_ownership(vectors: list[list[str]]) -> str:
    total = len(vectors)
    detailed = state_counts(vectors)
    lines = generated_preamble("VSM Harness Ownership by Function", total)
    lines += [
        "## Detailed ownership states",
        "",
        "Percentages use the full included corpus as denominator. `?` (unknown) remains distinct from `—` (no established path).",
        "",
        "| Function | A | A(P) | C | C(P) | P | — | ? | Total |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for function, counts in zip(FUNCTIONS, detailed):
        cells = [share(counts.get(state, 0), total) for state in STATES]
        lines.append("| " + " | ".join([function, *cells, str(total)]) + " |")

    lines += [
        "",
        "## Material-path categories",
        "",
        "This aggregate collapses states only for this view: Autonomous = `A + A(P)`; Constructor = `C + C(P)`; Parent-only = `P`; No path = `—`; Unknown = `?`.",
        "",
        "| Function | Autonomous | Constructor | Parent-only | No path | Unknown | Total |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for function, counts in zip(FUNCTIONS, detailed):
        collapsed = [
            counts.get("A", 0) + counts.get("A(P)", 0),
            counts.get("C", 0) + counts.get("C(P)", 0),
            counts.get("P", 0),
            counts.get("—", 0),
            counts.get("?", 0),
        ]
        lines.append(
            "| " + " | ".join([function, *(share(count, total) for count in collapsed), str(total)]) + " |"
        )
    lines.append("")
    return "\n".join(lines)


def render_organizational_forms(vectors: list[list[str]]) -> str:
    total = len(vectors)
    coverage = coverage_distribution(vectors)
    frequencies = vector_frequency(vectors)
    full_a = coverage.get(6, 0)
    near_full = coverage.get(5, 0)

    lines = generated_preamble("VSM Harness Organizational Forms", total)
    lines += [
        "## Autonomous-coverage distribution",
        "",
        "Autonomous coverage follows the existing base-state projection: `A(P)` counts as base `A`; no fractional score is assigned to `C`, `C(P)`, `P`, `—`, or `?`.",
        "",
        "| Agent-owned functions | Harnesses | Corpus share |",
        "| ---: | ---: | ---: |",
    ]
    for count in range(7):
        harnesses = coverage.get(count, 0)
        lines.append(f"| {count}/6 | {harnesses} | {100.0 * harnesses / total:.1f}% |")

    lines += [
        "",
        "## Descriptive incidence",
        "",
        f"- Full base-agent-owned coverage (6/6): **{share(full_a, total)}**.",
        f"- Exactly 5/6 base-agent-owned functions: **{share(near_full, total)}**.",
        "",
        "These are descriptive coverage incidences, not maturity tiers or quality labels.",
        "",
        "## Ownership-vector frequency",
        "",
        "| Ownership vector (S1 S2 S3 S3* S4 S5) | Harnesses | Corpus share |",
        "| --- | ---: | ---: |",
    ]
    for states, count in sorted(frequencies.items(), key=lambda item: (-item[1], item[0])):
        lines.append(f"| `{' '.join(states)}` | {count} | {100.0 * count / total:.1f}% |")
    lines.append("")
    return "\n".join(lines)


def render_matrix(title: str, matrix: list[list[int]]) -> list[str]:
    lines = [
        f"## {title}",
        "",
        "| Function | " + " | ".join(FUNCTIONS) + " |",
        "| --- | " + " | ".join(["---:"] * len(FUNCTIONS)) + " |",
    ]
    for function, row in zip(FUNCTIONS, matrix):
        lines.append("| " + " | ".join([function, *(str(value) for value in row)]) + " |")
    lines.append("")
    return lines


def render_cooccurrence(vectors: list[list[str]]) -> str:
    total = len(vectors)
    material = cooccurrence_matrix(vectors, lambda state: state in MATERIAL_STATES)
    autonomous = cooccurrence_matrix(vectors, lambda state: state in AUTONOMOUS_STATES)
    lines = generated_preamble("VSM Function Co-occurrence", total)
    lines += [
        "Cells are harness counts. Both matrices are symmetric; diagonal cells are the number of harnesses satisfying the corresponding single-function predicate.",
        "",
        "Material path means one of `A`, `A(P)`, `C`, `C(P)`, or `P`. Autonomous means `A` or `A(P)`.",
        "",
        *render_matrix("Material-path co-occurrence", material),
        *render_matrix("Autonomous co-occurrence", autonomous),
    ]
    return "\n".join(lines)


def render_reassessments(rows: list[dict[str, str]]) -> str:
    total = len(rows)
    changed_sets = [changed_functions(row) for row in rows]
    changed_events = sum(bool(functions) for functions in changed_sets)
    function_counts = Counter(function for functions in changed_sets for function in functions)
    outcomes = Counter(row.get("outcome", "") or "<missing>" for row in rows)
    by_version: dict[str, Counter[str]] = defaultdict(Counter)
    version_events = Counter()
    for row, functions in zip(rows, changed_sets):
        version = row.get("assessment_procedure_version", "") or "<missing>"
        version_events[version] += 1
        for function in functions:
            by_version[version][function] += 1

    lines = [
        "# VSM Harness Reassessment Aggregates",
        "",
        "Generated by `scripts/render_analytics.py` from `data/reassessment-history.psv`. Do not edit manually.",
        "",
        f"Recorded reassessment events: **{total}**. Events with one or more recorded changed functions: **{changed_events}**.",
        "",
        "Changed-function shares use changed reassessment events as denominator; one event may change multiple functions, so shares need not sum to 100%.",
        "",
        "## Changed functions",
        "",
        "| Function | Changed events | Share of changed events |",
        "| --- | ---: | ---: |",
    ]
    for function in FUNCTIONS:
        count = function_counts.get(function, 0)
        pct = 0.0 if changed_events == 0 else 100.0 * count / changed_events
        lines.append(f"| {function} | {count} | {pct:.1f}% |")

    lines += [
        "",
        "## Recorded outcomes",
        "",
        "Outcome names are taken directly from the history file rather than a hard-coded enum.",
        "",
        "| Outcome | Events | Share of all reassessments |",
        "| --- | ---: | ---: |",
    ]
    for outcome, count in sorted(outcomes.items(), key=lambda item: (-item[1], item[0])):
        pct = 0.0 if total == 0 else 100.0 * count / total
        lines.append(f"| `{outcome}` | {count} | {pct:.1f}% |")

    lines += [
        "",
        "## Changed functions by assessment-procedure version",
        "",
        "| Methodology | Events | S1 | S2 | S3 | S3* | S4 | S5 |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for version in sorted(version_events):
        counts = by_version[version]
        lines.append(
            "| "
            + " | ".join(
                [f"`{version}`", str(version_events[version]), *(str(counts.get(function, 0)) for function in FUNCTIONS)]
            )
            + " |"
        )
    lines.append("")
    return "\n".join(lines)


def render_all(repo: Path) -> dict[Path, str]:
    included = load_included(repo)
    vectors = [states for _, states in included]
    validate_aggregates(vectors)
    reassessments = read_psv(repo / "data" / "reassessment-history.psv")
    return {
        repo / "analytics" / "ownership.md": render_ownership(vectors),
        repo / "analytics" / "organizational-forms.md": render_organizational_forms(vectors),
        repo / "analytics" / "cooccurrence.md": render_cooccurrence(vectors),
        repo / "analytics" / "reassessments.md": render_reassessments(reassessments),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    outputs = render_all(repo)
    if args.check:
        stale = [
            str(path)
            for path, text in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8") != text
        ]
        if stale:
            raise SystemExit("stale generated analytics file(s): " + ", ".join(stale))
    else:
        for path, text in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
