#!/usr/bin/env python3
"""Render the autonomy-centered VSM TLDR projection."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


TLDR_BEGIN = "<!-- BEGIN GENERATED VSM TLDR -->"
TLDR_END = "<!-- END GENERATED VSM TLDR -->"
CURRENT_RUBRIC = "vsm-assessment/v2"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def read_catalog(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle, delimiter="|"))
    for row in rows:
        row["vsm_tldr"] = row["vsm_tldr"].replace("\\n", "\n")
    return sorted(rows, key=lambda row: int(row["catalog_position"]))


def markdown(value: str) -> str:
    return " ".join(value.split()).replace("|", "\\|")


def markdown_multiline(value: str) -> str:
    rendered = []
    for line in value.splitlines():
        system, separator, description = line.partition(":")
        if separator:
            rendered.append(f"<strong>{markdown(system)}:</strong> {markdown(description)}")
        else:
            rendered.append(markdown(line))
    return "<br>".join(rendered)


def latest_assessments(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    latest: dict[str, dict[str, str]] = {}
    for row in rows:
        harness_id = row["harness_id"]
        candidate = (row.get("generated_at", ""), row.get("assessment_id", ""))
        incumbent = latest.get(harness_id)
        if incumbent is None or candidate > (
            incumbent.get("generated_at", ""),
            incumbent.get("assessment_id", ""),
        ):
            latest[harness_id] = row
    return sorted(
        latest.values(),
        key=lambda row: (
            int(row.get("catalog_position", "999999")),
            row.get("project_name", "").casefold(),
        ),
    )


def current_assessments(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    return latest_assessments(
        [row for row in rows if row.get("rubric_version") == CURRENT_RUBRIC]
    )


def catalog_label(harness: dict[str, str], detailed: bool) -> str:
    year = harness["repository_created_at"][:4]
    label = markdown(f"{harness['project_name']} ({year})")
    target = (
        f"entries/{harness['harness_id']}.md"
        if detailed
        else harness["repository"]
    )
    return f"[{label}]({target})"


def render_tldr_block(repo: Path) -> str:
    harnesses = [
        row
        for row in read_catalog(repo / "data" / "catalog.psv")
        if row.get("tldr_status", "included") == "included"
    ]
    assessments = {
        row["harness_id"]: row
        for row in current_assessments(read_csv(repo / "data" / "harnesses.csv"))
    }
    lines = [
        TLDR_BEGIN,
        "<!-- Generated by scripts/render_readme.py; edit data/catalog.psv or a detailed assessment override. -->",
    ]
    if not harnesses:
        lines.append("No current VSM TL;DR assessments yet.")
    else:
        lines.extend(
            [
                "| Harness | VSM TL;DR |",
                "| --- | --- |",
            ]
        )
        for harness in reversed(harnesses):
            detailed = harness["harness_id"] in assessments
            tldr = assessments.get(harness["harness_id"], harness).get("vsm_tldr", "")
            lines.append(
                f"| {catalog_label(harness, detailed)} | {markdown_multiline(tldr)} |"
            )
    lines.append(TLDR_END)
    return "\n".join(lines)


def render_tldr_document(repo: Path) -> str:
    return "\n".join(
        [
            "# VSM Harness TL;DR",
            "",
            "Compact autonomy-centered fingerprints for the current discovery cohort.",
            "Every included row shows S1, S2, S3, S3*, S4, and S5.",
            "",
            "| Symbol | State | Meaning |",
            "| --- | --- | --- |",
            "| `A` | Agent-owned | Ready agent-owned enactment is available through the standard documented setup. |",
            "| `C` | Composable | A first-party primitive is supplied, but the developer must compose the agent, authority, or feedback loop. |",
            "| `P` | Parent-assisted | Runtime closure returns a parent identity or ultimate-policy decision to subsequent operation; valid only for S5. |",
            "| `—` | No supplied path | The review boundary supports no material first-party path; this is not proof that one can never be built. |",
            "| `?` | Unknown | The reviewed primary evidence is insufficient to establish the state. |",
            "",
            "Assessments are processed by ascending catalog position before",
            "cross-catalog distinctions are finalized. Rows are displayed by GitHub",
            "repository creation time, newest first. The displayed year is the repository creation",
            "year, not necessarily the first agent-capable release.",
            "",
            "Catalog-only rows are source-derived hypotheses. Projects whose standard",
            "documented setup does not establish an autonomous decision/action loop are",
            "excluded as NO AGENTIC VSM.",
            "Detailed assessments override them by `harness_id`. See [methodology](METHODOLOGY.md) and",
            "[sources and licensing](SOURCES.md).",
            "",
            render_tldr_block(repo),
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    tldr_path = repo / "TLDR.md"
    rendered_tldr = render_tldr_document(repo)
    if args.check:
        if not tldr_path.exists() or tldr_path.read_text(encoding="utf-8") != rendered_tldr:
            raise SystemExit("TLDR projection is stale; run scripts/render_readme.py")
        print("TLDR projection is current")
        return 0
    tldr_path.write_text(rendered_tldr, encoding="utf-8")
    print(tldr_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
